- inu-phonebook/src/main/java/com/example/inuphonebook/domain/Professor.java
> fix: photo -> imageUrl 속성 타입 수정

- inu-phonebook/src/main/java/com/example/inuphonebook/domain/College.java
- inu-phonebook/src/main/java/com/example/inuphonebook/domain/Department.java
- inu-phonebook/src/main/java/com/example/inuphonebook/domain/Employee.java
- inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepository.java
- 직원 테이블 이미지 속성 추가
- 도메인 nullable 옵션 추가
- @Repository 추가
> [Develop] domain 수정

- .idea/gradle.xml
- inu-phonebook/src/main/java/com/example/inuphonebook/controller/EmployeeController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/dto/employee/EmployeeReqDto.java
- inu-phonebook/src/main/java/com/example/inuphonebook/dto/employee/EmployeeRespDto.java
- inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepository.java
- inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepositoryCustom.java
- inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepositoryCustomImpl.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/EmployeeService.java
- inu-phonebook/src/main/resources/application-dev.yml
#12 
조회관련 리포지토리 및 서비스 추가
Message, Exception을 가지고 컨트롤러에서 어떤 형식으로 리턴해주는지 잘 몰라서 냅뒀습니다.
> [feat] 조회관련 리포지토리 및 서비스 추가

- inu-phonebook/src/main/java/com/example/inuphonebook/controller/CrawlingController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/domain/Employee.java
- inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepository.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/ImageCrawlingService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/humanities/KoreanDepartment.java
학과 하나만 구현해봤는데 이대로 해도 좋을지 확인 부탁드립니다.
생각해보니 이미지 테이블 굳이 넣지 않고 바로 Employee 필드에 넣어주면 되는 것 같아서 바꿨습니ㅏㄷ.
> 사진 크롤링 기능 예시

- inu-phonebook/src/main/java/com/example/inuphonebook/InuPhonebookApplication.java
- inu-phonebook/src/main/java/com/example/inuphonebook/controller/CrawlingController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/HumanityDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/NaturalScienceDepartmentService.java
#16 
@Scheduled 테스트에 따른 메서드 수정 및 자연과학대학 크롤링 추가
> [feat] @Scheduled 추가 메서드 수정

- inu-phonebook/src/main/java/com/example/inuphonebook/common/Constants.java
- inu-phonebook/src/main/java/com/example/inuphonebook/controller/CrawlingController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/dto/ResponseDto.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/ImageCrawlingService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/EngineeringDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/GlobalLandscapeDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/HumanityDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/NaturalScienceDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/SocialScienceDepartmentService.java
#16 
-  대부분 학과사이트의 크롤링 구조가 동일해서 인터페이스에 default 메서드로 변경했습니다.
- 공통url을 특정 클래스에 public static final로 선언해서 같은걸로 가져오게 변경했습니다.
- iframe 내부의 웹 페이지 크롤링하는 메서드 추가
> [feat] 사회과학대학 크롤링 중 구조변경

- inu-phonebook/src/main/java/com/example/inuphonebook/common/Constants.java
- inu-phonebook/src/main/java/com/example/inuphonebook/controller/CrawlingController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/controller/EmployeeController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/ImageCrawlingService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/EngineeringDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/GlobalLandscapeDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/HumanityDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/InformationTechnologyDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/SocialScienceDepartmentService.java
- inu-phonebook/src/main/resources/application-dev.yml
#16 
EmployeeController url 수정, url 상수 환경변수로 변경
> [refactor] url 수정

- inu-phonebook/src/main/java/com/example/inuphonebook/controller/CrawlingController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/ImageCrawlingService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/InformationTechnologyDepartmentService.java
#16 
정보기술대학 크롤링 완료 및 임베디드 학과 페이지 전용 로직 추가(상세보기 페이지)
> [feat] 임베디드학과용 상세보기 로직 추가

- inu-phonebook/src/main/java/com/example/inuphonebook/controller/CrawlingController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/ImageCrawlingService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/AdministrationDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/ArtSportDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/EducationDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/LawDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/LifeScienceDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/NortheastAsiaDepartmentService.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/departmentCrawling/UrbanScienceDepartmentService.java
- inu-phonebook/src/main/resources/application-dev.yml
> [feat] 학과 크롤링 구현 완료

- .github/workflows/gradle.yml
- Dockerfile
[#18 ](https://github.com/Unionz-CallinU/INU-phonebook-server/issues/18)
CI/CD 깃헙액션 작성, Dockerfile 작성
Github Screct에 환경에 맞는 변수 내용을 추가해주세요.  
필요한 변수는 다음과 같습니다.
| 변수 이름 | 필요한 내용 |
| :-------: | :---------: |
| PROPERTIES | `application.properties` 파일 내용 |
| DOCKER_USERNAME | 도커 계정 username |
| DOCKER_PASSWORD | 도커 계정 비밀번호 |
| DOCKER_REPO | 도커 레포지토리 이름 |
| HOST_ADDRESS | 서버 주소 |
| SERVER_USERNAME | 서버 사용자 이름 |
| SERVER_PASSWORD | 서버 비밀번호 |
- AWS ec2에 배포하는 것을 기준으로 깃헙액션과 도커파일을 작성했습니다. 따라서 앱센터 서버에 배포하려면 추가로 Caddy파일을 설정해야합니다. 
- DB 관련 설정은 하지 않았습니다. (RDS 할줄 모름)
> [feat] github Action CI/CD + Dockerfile 작성

- .github/workflows/gradle.yml
- inu-phonebook/src/main/resources/application-dev.yml
> [chore] update gradle.yml

- inu-phonebook/.gitignore
- application.yml 파일 ignore 추가
> [chore] update .gitignore

- inu-phonebook/src/main/java/com/example/inuphonebook/common/aop/CustomTruncateAdvice.java
- inu-phonebook/src/main/java/com/example/inuphonebook/controller/CrawlingController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/controller/EmployeeController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/domain/Employee.java
- inu-phonebook/src/main/java/com/example/inuphonebook/dto/employee/EmployeeReqDto.java
- inu-phonebook/src/main/java/com/example/inuphonebook/dto/employee/EmployeeRespDto.java
- inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepositoryCustomImpl.java
- inu-phonebook/src/main/java/com/example/inuphonebook/service/INUCrawlingService.java
- inu-phonebook/src/main/resources/application-dev.yml
EmployeeRepository에 jpaql 문법 오타 수정, search 대상을 college -> department로 변경
크롤링 시, 중복 데이터 문제 때문에 크롤링 전마다 데이터베이스를 비우고 primary key를 초기화할 어드바이스를 추가했습니다.
> [fix,feat] 리포지토리 오타 및 수정, advice 추가

- inu-phonebook/src/main/resources/application-dev.yml
> [fix] Fix application-dev.yml

- .github/workflows/CD.yml
- .github/workflows/CI.yml
> feat: upload CI/CD yml file

- inu-phonebook/src/main/java/com/example/inuphonebook/controller/EmployeeController.java
#42 
- 검색 기능 Get -> Post 매핑으로 코드 변경
> [fix] getMapping -> postMapping 검색 기능 수정

- .github/workflows/CI.yml
> fix: Fix CI.yml

- inu-phonebook/build.gradle
- inu-phonebook/src/main/java/com/example/inuphonebook/MyApplicationRunner.java
- inu-phonebook/src/main/java/com/example/inuphonebook/config/SwaggerConfig3.java
- inu-phonebook/src/main/java/com/example/inuphonebook/controller/EmployeeController.java
- inu-phonebook/src/main/java/com/example/inuphonebook/dto/employee/EmployeeRespDto.java
- inu-phonebook/src/main/resources/application-dev.yml
> [fix] response example value 값 보이게 수정

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- inu-phonebook/.gitignore
- inu-phonebook/src/main/resources/application-prod.yml
- inu-phonebook/src/main/resources/application.yml
- inu-phonebook/src/test/java/com/example/inuphonebook/service/INUCrawlingServiceTest.java
> fix: Fix CI/CD yml file

- .github/workflows/CD.yml
> fix: fix CD.yml

- inu-phonebook/src/main/resources/application-prod.yml
> fix: application-prod.yml 수정

- inu-phonebook/src/main/java/com/example/inuphonebook/repository/EmployeeRepositoryCustomImpl.java
> [feat] 대학 별 조회 기능 추가
